### ISSUE TITLE
Game crashes when clicking on "Respawn" Button.

### ISSUE THREAD

**Issue by Linusintro** [Jeryn99/Gliders#63]
If you die and click the "Respawn" Button the Game Crashes.
Here is the Crash Report:
`---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-05-09 18:19:14
Description: Exception in server tick loop

java.lang.IllegalAccessError: class dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity tried to access private field net.minecraft.class_1297.field_6002 (dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @9629756)
	at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.copyData(CardinalComponentsEntity.java:64)
	at dev.onyxstudios.cca.api.v3.entity.PlayerCopyCallback.lambda$static$0(PlayerCopyCallback.java:38)
	at net.minecraft.class_3222.handler$zze000$cardinal-components-entity$copyDataFrom(class_3222.java:1871)
	at net.minecraft.class_3222.method_14203(class_3222.java:1238)
	at net.minecraft.class_3324.method_14556(class_3324.java:504)
	at net.minecraft.class_3244.method_12068(class_3244.java:1632)
	at net.minecraft.class_2799.method_12120(class_2799.java:24)
	at net.minecraft.class_2799.method_11054(class_2799.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-105-generic
	Java Version: 17.0.11, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1660713472 bytes (1583 MiB) / 2390753280 bytes (2280 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Polaris 20 XL [Radeon RX 580 2048SP]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x6fdf
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10010.16
	Virtual memory used (MB): 7685.14
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.75
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		clearvoid: Clear Void 1.3.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.57
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabrication: Fabrication 3.4.14+1.20
			lib39-deferral: Lib39 (Deferral) 1.5.0-pre2.2+1.19.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.0.1
		immediatelyfast: ImmediatelyFast 1.2.14+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.4
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		mr_aetherial_islands: Aetherial Islands 1-v1.0.2
		mr_no_moreshipwrecks: No More Shipwrecks 1.0.0
		mr_recipes_plus: Recipes Plus 1.4
		no_void_structures: No_void_structures 1.0.0
		norecipebook: NoRecipeBook 2.4+1.20.1
		paper_recipes: New Paper Recipes 1.0.0
		preferred-gamerules: Preferred Gamerules 1.1.0+1.19.4
		skyvillages: SkyVillages 1.0.2
		sodium: Sodium 0.5.8+mc1.20.1
		spark: spark 1.10.53
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.1.2+fabric.dbc156f
		superflatworldnoslimes: Superflat World No Slimes 3.2
		threadtweak: ThreadTweak 1.20.2-0.1.1
		vc_gliders: Gliders 1.1.5
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			palladiumcore: PalladiumCore 1.20-2.0.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		wooltweaks: Wool Tweaks 3.3
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1`

**Comment by owosoup** [comment]
For me, the game just hangs after clicking the respawn button. A little text says "Performing respawn..." but nothing happens. You have to quit, disable the mod, then rejoin and respawn in your world.

**Comment by Jeryn99** [comment]
> For me, the game just hangs after clicking the respawn button. A little text says "Performing respawn..." but nothing happens. You have to quit, disable the mod, then rejoin and respawn in your world.

I will need logs from you, I sadly cannot remote view them :(
I am aware the person who created the issue supplied one, but you must also supply one as it could be different from person to person - your issue doesn't seem to result in a crash like theirs does

**Comment by owosoup** [comment]
I haven't been able to reproduce it in a different world yet. It's really weird, I'll show logs once I get it.

**Comment by Kenshelent** [comment]
install this https://modrinth.com/mod/cardinal-components-api/version/5.0.0
